// Generated by Weather Tuning Studio
// Exported at: 2026-02-10T02:41:39.557Z
//
// NOTE: This file was reset to empty presets due to type mismatches.
// The original file had properties (glass, post, haze, glassIntensity, etc.)
// that don't exist in WeatherEffectsOverrides interface.
// Backup available at: tuned-presets.ts.backup

import type { WeatherCondition } from "../schema";
import type { WeatherEffectsCheckpointOverrides } from "./tuning";

export const TUNED_WEATHER_EFFECTS_CHECKPOINT_OVERRIDES: Partial<
  Record<WeatherCondition, WeatherEffectsCheckpointOverrides>
> = {};
